### ISSUE TITLE
Add release tracking. 

### ISSUE THREAD

**Issue by octalmage** [octalmage/gatsby-plugin-sentry#1]
Release tracking is super nice. Use the package version, or even a build hash to keep track of regressions and resolutions.

**Comment by mhadaily** [comment]
I have an example for those who like to see how they can add, let's assume you have installed `git-rev-sync` library, therefore, you can have something like this: 

```
options: {
    // Optional settings, see https://docs.sentry.io/clients/node/config/#optional-settings
    dsn: "DSN",
    config: {
      environment: process.env.NODE_ENV,
      tags: { git_commit: require('git-rev-sync').short() },
      release: require('git-rev-sync').long(),
    },
  },

```

**Comment by kristojorg** [comment]
@mhadaily what file/gatsby api are you using this in? `git-rev-sync` doesn't work in the browser I don't believe, so I can't use it in `gatsby-browser.js` where I am initializing sentry

**Comment by mhadaily** [comment]
@kristojorg git-rev doesn't work in the browser but that's not what this does here. Basically,`require('git-rev-sync').long()` and `require('git-rev-sync').short()` will be replace by the value on build time and therefore on the browser you will have only a hash/number.

**Comment by kristojorg** [comment]
Aha thank you! I had switched my file to use es6 imports instead of require and now I see why that doesn't work. Cheers 

Edit: it actually wan't because I was using es6 import. It was because I was calling `git-rev-sync` in `gatsby-browser.js` instead of in `gatsby-config.js`, which is run at build time.

**Comment by octalmage** [comment]
I’m going to consider this done!
