### ISSUE TITLE
Extra gatsby-ssr.js file in npm package

### ISSUE THREAD

**Issue by browniebroke** [octalmage/gatsby-plugin-sentry#13]
I'm not sure why I'm getting this given that it was removed in #9, but I've installed the latest version (1.0.0) from NPM, and there is a extra `gatsby-ssr.js` in the installed version of `gatsby-plugin-sentry` I'm getting in my `node_modules`.

I don't think it's causing any problems for me, but it looks like something went wrong when deploying the latest release.

**Comment by octalmage** [comment]
Good catch! I'll get that fixed. Thanks1

**Comment by humphreybc** [comment]
Found this one too. I _think_ this is causing the script tag to be added to the head and the JS to be loaded synchronously from the ravenjs.com CDN. This is causing some performance issues (indeed [PageSpeed Insights doesn't like it at all](https://i.imgur.com/bjR2aKm.png)) and basically makes [this issue](https://github.com/octalmage/gatsby-plugin-sentry/issues/5) still a problem.

Would be great to get an ETA on a fix! :)

**Comment by mhadaily** [comment]
@humphreybc Yes, it loads synchronously and of course, we can load it asynchronously, however, there is a limitation as of now which is, Sentry will capture only global errors and unhandled promise until it will be fully loaded and available, if anything happens during download and initialization like an error in XHR request, click on something or anything similar, it will not be captured. 

I think it's good to have both Sync and Async option for this plugin and it should be up to the user to choose whether they want Lazy load or synchronous load.  what do you think @humphreybc  and @octalmage? (BTW, I can sed a PR for this if everyone agrees)

**Comment by humphreybc** [comment]
@mhadaily Yeah, an `async: true` option that we could set in `gatsby-config` would be awesome.

**Comment by antoinerousseau** [comment]
Why load Sentry both as a CDN script tag in `gatsby-ssr.js` AND an NPM package in `gatsby-browser.js`? Wouldn't the latter be enough?

**Comment by mhadaily** [comment]
@antoinerousseau I suppose gatsby-ssr.js is extra and will be removed, @octalmage is working on it.

**Comment by humphreybc** [comment]
It would be great to get a fix for this. Unfortunately we've had to disable this plugin for now because it's destroying our page speed score. Would love to re-enable it.

**Comment by octalmage** [comment]
The fix has been deployed as v1.0.1. Really not sure what happened there, let me know if you still encounter issues!
