### ISSUE TITLE
Make script loading async?

### ISSUE THREAD

**Issue by KyleAMathews** [octalmage/gatsby-plugin-sentry#5]
Currently you're adding the script into the head which will block the page loading until the script is downloaded.

/cc @mickeyreiss-visor

**Comment by KyleAMathews** [comment]
Want to add sentry support to gatsbyjs.org but need this fixed first :-)

Also @mickeyreiss-visor's PR looks good to me.

Oh and here's a long issue about this https://github.com/getsentry/raven-js/issues/169

**Comment by KyleAMathews** [comment]
Possibly one of the solutions there could be a good fit.

**Comment by sedubois** [comment]
@KyleAMathews did you workaround this somehow or you still don't have Sentry in Gatsbyjs.org?

**Comment by gilesbutler** [comment]
Interested to hear if you got this going too @KyleAMathews.

We had to turn Sentry off due to lots of errors coming from the Gatsby generated code.

**Comment by octalmage** [comment]
Thanks guys! I'll take a look at making it async.

**Comment by octalmage** [comment]
@gilesbutler I get a good number of errors as well on my site, but they are legit errors that mean that the user had to click a link twice or something like that. I think it's worth keeping it enabled to check out.

**Comment by KyleAMathews** [comment]
Oh, instead of pulling it from a CDN, this plugin should just add it directly via their NPM package https://docs.sentry.io/clients/javascript/install/#npm

`onClientEntry` makes this sort of thing pretty easy for a plugin to do https://www.gatsbyjs.org/docs/browser-apis/#onClientEntry

**Comment by octalmage** [comment]
There's related talk in #6 about how to pull the library in. I agree and I'd like to get it to pull from npm. I just copied the Google Analytics plugin to get Sentry loading on my site.

**Comment by humphreybc** [comment]
@octalmage Any update on pulling from NPM?

**Comment by Thien42** [comment]
I sent a pull request regarding the loading from NPM instead of the CDN #9

**Comment by abumalick** [comment]
I have to remove the plugin because of that, scripts are usually never added to the `<head>`

**Comment by octalmage** [comment]
Version v0.1.0 has been published to npm which resolves this, and it's also been deployed to my site https://jason.stallin.gs and appears to be working. Got some errors related to cached bundles so I got to see it work in production. 

Thanks everyone!
