### ISSUE TITLE
default ravenjs version is too old and does not stay up to date

### ISSUE THREAD

**Issue by sedubois** [octalmage/gatsby-plugin-sentry#6]
Sentry warns that the lib is too old when leaving the default version `3.19.1`:

<img width="993" alt="screen shot 2018-02-18 at 15 00 08" src="https://user-images.githubusercontent.com/4217871/36352099-7a0d2e76-14bc-11e8-8901-e03c9cf6c48a.png">

A temporary workaround is to override `version` (currently seems to be `3.22.3`), but it will soon be outdated as well, and updating this can't be automated with tools such as [renovateapp.com](https://renovateapp.com) because the plugin is referring to the CDN, not to the NPM dependency.

The ideal would be for the plugin to use the latest version by default. Could using the NPM dependency solve this?

**Comment by octalmage** [comment]
On my own site I just update the version prop. I added a default to make the plugin easier to use but I think the prop is the way to go. I personally lock dependencies and update them manually. 

I'm not against using the NPM version though!

**Comment by sedubois** [comment]
Yeah I don't know how to do this but if we could use the NPM dep it should solve the issue nicely (keep version locked, but get an automatic pull request from renovate, greenkeeper or other when newer lib is available).
